<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Core file integrity scanner.
 *
 * @package    local_sentinel
 * @copyright  2026 David Pesce - Exputo Inc.
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

namespace local_sentinel;

/**
 * Diffs the on-disk Moodle code tree against a dashboard-provided manifest.
 *
 * The manifest lists the git blob SHA-1 of every file in the pristine tree
 * for this site's exact build (see the moodle-core-manifests repository).
 * The scan walks the code root, hashes files the same way git does, and
 * records three kinds of deviation:
 *
 * - modified:   present in the manifest, hash differs on disk
 * - missing:    present in the manifest, absent on disk
 * - unexpected: on disk, not in the manifest (reported by path ONLY — no
 *               hash or size, so a stray secret-bearing file can never be
 *               fingerprinted off-site)
 *
 * Only deviations leave the site. Interpretation (suspicious vs benign,
 * alerting, history) is the dashboard's job.
 */
class integrity_scanner {
    /** Cap per deviation list; counts beyond it are reported as overflow. */
    public const MAX_DEVIATIONS = 500;

    /** Abort the walk after this much wall-clock time. */
    public const MAX_RUNTIME_SECONDS = 600;

    /** Cap on recorded per-file read errors. */
    public const MAX_ERRORS = 20;

    /** Files larger than this are hashed incrementally. */
    private const STREAM_THRESHOLD = 20 * 1024 * 1024;

    /**
     * The directory the manifest paths are relative to.
     *
     * Moodle 5.1 moved the webroot to public/ and introduced $CFG->root for
     * the repository root; manifests carry public/-prefixed paths there. On
     * 4.x, dirroot IS the repository root.
     *
     * @return string
     */
    public static function base_dir(): string {
        global $CFG;
        return !empty($CFG->root) ? $CFG->root : $CFG->dirroot;
    }

    /**
     * Git blob hash of a file: sha1("blob <size>\0" + content).
     *
     * Matches `git hash-object` so manifest entries generated by
     * `git ls-tree` compare directly against on-disk files.
     *
     * @param string $filepath Absolute path.
     * @return string|null Null when the file cannot be read.
     */
    public static function git_blob_sha1(string $filepath): ?string {
        if (is_link($filepath)) {
            // Git stores a symlink as a blob whose content is the target path.
            $target = @readlink($filepath);
            if ($target === false) {
                return null;
            }
            return sha1('blob ' . strlen($target) . "\0" . $target);
        }
        $size = @filesize($filepath);
        if ($size === false) {
            return null;
        }
        if ($size > self::STREAM_THRESHOLD) {
            $context = hash_init('sha1');
            hash_update($context, 'blob ' . $size . "\0");
            $handle = @fopen($filepath, 'rb');
            if ($handle === false) {
                return null;
            }
            hash_update_stream($context, $handle);
            fclose($handle);
            return hash_final($context);
        }
        $content = @file_get_contents($filepath);
        if ($content === false) {
            return null;
        }
        return sha1('blob ' . strlen($content) . "\0" . $content);
    }

    /**
     * Base-relative path prefixes excluded from the walk.
     *
     * Excluded because they are legitimately absent from the pristine tree:
     * config.php, VCS metadata, dependency dirs from dev installs, a nested
     * dataroot, and the directories of installed NON-standard plugins (those
     * are already covered by the plugins slice). Everything else on disk
     * that is not in the manifest is reported as unexpected — that is the
     * point of the scan.
     *
     * @return string[]
     */
    public static function excluded_prefixes(): array {
        global $CFG;
        $base = rtrim(self::base_dir(), '/');
        $prefixes = ['.git', 'vendor', 'node_modules', 'config.php', 'public/config.php'];

        $dataroot = rtrim((string) $CFG->dataroot, '/');
        if ($dataroot !== '' && str_starts_with($dataroot, $base . '/')) {
            $prefixes[] = substr($dataroot, strlen($base) + 1);
        }

        // Plugin enumeration can echo stray output (e.g. whitespace after a
        // closing PHP tag in some third-party version.php); suppress it so
        // cron logs and WS responses stay clean — same guard as the plugins
        // collector.
        ob_start();
        try {
            $pluginman = \core_plugin_manager::instance();
            foreach ($pluginman->get_plugins() as $type => $plugins) {
                $standard = \core_plugin_manager::standard_plugins_list($type);
                if (!is_array($standard)) {
                    $standard = [];
                }
                foreach ($plugins as $name => $info) {
                    if (in_array($name, $standard, true)) {
                        continue;
                    }
                    $rootdir = (string) ($info->rootdir ?? '');
                    if ($rootdir !== '' && str_starts_with($rootdir, $base . '/')) {
                        $prefixes[] = substr($rootdir, strlen($base) + 1);
                    }
                }
            }
        } finally {
            ob_end_clean();
        }
        return $prefixes;
    }

    /**
     * Run the scan against the stored manifest.
     *
     * @return array Result with status, counts, capped deviation lists and
     *               metadata. Status 'error' carries an error message.
     */
    public static function scan(): array {
        global $CFG;
        \core_php_time_limit::raise(self::MAX_RUNTIME_SECONDS + 60);
        raise_memory_limit(MEMORY_EXTRA);

        $result = [
            'status' => 'error',
            'error' => '',
            'scanned_at' => time(),
            'duration_seconds' => 0,
            'manifest_version' => '',
            'manifest_version_mismatch' => false,
            'files_scanned' => 0,
            'modified_count' => 0,
            'missing_count' => 0,
            'unexpected_count' => 0,
            'modified' => [],
            'missing' => [],
            'unexpected' => [],
            'modified_overflow' => 0,
            'missing_overflow' => 0,
            'unexpected_overflow' => 0,
            'errors' => [],
        ];

        $meta = manifest_store::load_meta();
        $manifest = manifest_store::load_manifest_map();
        if ($meta === null || $manifest === null) {
            $result['error'] = 'no manifest stored';
            return $result;
        }
        $result['manifest_version'] = (string) $meta['version'];
        $result['manifest_version_mismatch'] = ((string) $meta['version']) !== ((string) $CFG->version);

        $base = rtrim(self::base_dir(), '/');
        $excluded = self::excluded_prefixes();
        $start = microtime(true);

        $directory = new \RecursiveDirectoryIterator($base, \FilesystemIterator::SKIP_DOTS);
        $filter = new \RecursiveCallbackFilterIterator(
            $directory,
            function ($current) use ($base, $excluded): bool {
                $rel = self::relative_path($base, $current->getPathname());
                return !self::is_excluded($rel, $excluded);
            }
        );
        $iterator = new \RecursiveIteratorIterator($filter);

        $scanned = 0;
        $timedout = false;
        foreach ($iterator as $fileinfo) {
            if (!$fileinfo->isFile() && !$fileinfo->isLink()) {
                continue;
            }
            $scanned++;
            if (($scanned % 256) === 0 && (microtime(true) - $start) > self::MAX_RUNTIME_SECONDS) {
                $timedout = true;
                break;
            }
            $rel = self::relative_path($base, $fileinfo->getPathname());
            if (array_key_exists($rel, $manifest)) {
                // Hash only files we have a reference for. Unexpected files
                // are deliberately never hashed (path-only reporting).
                $hash = self::git_blob_sha1($fileinfo->getPathname());
                if ($hash === null) {
                    if (count($result['errors']) < self::MAX_ERRORS) {
                        $result['errors'][] = 'unreadable: ' . $rel;
                    }
                } else if ($manifest[$rel] !== $hash) {
                    $result['modified_count']++;
                    if (count($result['modified']) < self::MAX_DEVIATIONS) {
                        $result['modified'][] = [
                            'path' => $rel,
                            'expected_sha1' => $manifest[$rel],
                            'actual_sha1' => $hash,
                        ];
                    }
                }
                // Whatever remains in the map after the walk is missing.
                unset($manifest[$rel]);
            } else {
                $result['unexpected_count']++;
                if (count($result['unexpected']) < self::MAX_DEVIATIONS) {
                    $result['unexpected'][] = $rel;
                }
            }
        }
        $result['files_scanned'] = $scanned;
        $result['duration_seconds'] = (int) round(microtime(true) - $start);

        if ($timedout) {
            $result['error'] = "timeout after {$scanned} files (" . self::MAX_RUNTIME_SECONDS . 's limit)';
            return $result;
        }

        foreach ($manifest as $rel => $unused) {
            if (self::is_excluded($rel, $excluded)) {
                continue;
            }
            $result['missing_count']++;
            if (count($result['missing']) < self::MAX_DEVIATIONS) {
                $result['missing'][] = $rel;
            }
        }

        $result['modified_overflow'] = max(0, $result['modified_count'] - count($result['modified']));
        $result['missing_overflow'] = max(0, $result['missing_count'] - count($result['missing']));
        $result['unexpected_overflow'] = max(0, $result['unexpected_count'] - count($result['unexpected']));
        $result['status'] = 'ok';
        return $result;
    }

    /**
     * Orchestrator used by both the scheduled and adhoc tasks.
     *
     * Self-gates on the setting and manifest presence so the scheduled task
     * can stay enabled in db/tasks.php (same pattern as push_snapshot).
     */
    public static function run(): void {
        if (!(bool) get_config('local_sentinel', 'integrityenabled')) {
            mtrace('local_sentinel: integrity scanning disabled in settings, skipping.');
            return;
        }
        if (manifest_store::load_meta() === null) {
            mtrace('local_sentinel: no integrity manifest stored (the dashboard provisions one), skipping.');
            return;
        }
        try {
            $result = self::scan();
        } catch (\Throwable $e) {
            integrity_state::record_scan_error($e->getMessage());
            mtrace('local_sentinel: integrity scan failed: ' . $e->getMessage());
            return;
        }
        manifest_store::save_scan_result($result);
        if ($result['status'] === 'ok') {
            integrity_state::record_scan_ok($result);
            mtrace(sprintf(
                'local_sentinel: integrity scan ok — %d files, %d modified, %d missing, %d unexpected (%ds).',
                $result['files_scanned'],
                $result['modified_count'],
                $result['missing_count'],
                $result['unexpected_count'],
                $result['duration_seconds']
            ));
        } else {
            integrity_state::record_scan_error($result['error']);
            mtrace('local_sentinel: integrity scan error: ' . $result['error']);
        }
    }

    /**
     * Base-relative path with forward slashes.
     *
     * @param string $base Absolute base directory, no trailing slash.
     * @param string $path Absolute path inside $base.
     * @return string
     */
    protected static function relative_path(string $base, string $path): string {
        $rel = substr($path, strlen($base) + 1);
        return str_replace('\\', '/', (string) $rel);
    }

    /**
     * Whether a relative path is (or is inside) an excluded prefix.
     *
     * @param string   $rel      Base-relative path.
     * @param string[] $excluded Excluded prefixes.
     * @return bool
     */
    protected static function is_excluded(string $rel, array $excluded): bool {
        foreach ($excluded as $prefix) {
            if ($rel === $prefix || str_starts_with($rel, $prefix . '/')) {
                return true;
            }
        }
        return false;
    }
}
